descargas:
    path:     /
    defaults: { _controller: "SegurexBundle:Descargas:index" }

descargas_show:
    path:     /{id}/show
    defaults: { _controller: "SegurexBundle:Descargas:show" }

descargas_new:
    path:     /new
    defaults: { _controller: "SegurexBundle:Descargas:new" }

descargas_create:
    path:     /create
    defaults: { _controller: "SegurexBundle:Descargas:create" }
    requirements: { _method: post }

descargas_edit:
    path:     /{id}/edit
    defaults: { _controller: "SegurexBundle:Descargas:edit" }

descargas_update:
    path:     /{id}/update
    defaults: { _controller: "SegurexBundle:Descargas:update" }
    requirements: { _method: post|put }

descargas_delete:
    path:     /{id}/delete
    defaults: { _controller: "SegurexBundle:Descargas:delete" }
    requirements: { _method: post|delete }
